spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/order_manager
    username: root
    password: p@ssAdm7

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true    # 开启 knife4j，无需添加 @EnableKnife4j 注解
  setting:
    language: zh_cn   # 中文
    swagger-model-name: 实体类   # 重命名 SwaggerModel 名称,默认

app:
  token:
    store: true
    store-path: /Users/lgx/Documents/Projects.localized/2024/java/order-manager/backend/tokens
    max-inactive-interval: 1800  # 令牌失效时间
